# Generated by Django 5.1.1 on 2024-09-26 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_timer_current_responsible_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contractor',
            new_name='contractors',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='customer',
            new_name='customers',
        ),
    ]
