# Generated by Django 5.1.1 on 2024-09-26 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_project_contractors_remove_project_customers_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractors',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customers',
        ),
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(related_name='contractor_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='customers',
            field=models.ManyToManyField(related_name='customer_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
