# Generated by Django 5.1.1 on 2024-10-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_project_contractors_remove_project_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='question',
        ),
        migrations.RemoveField(
            model_name='project',
            name='question_file',
        ),
        migrations.AddField(
            model_name='task',
            name='question',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='question_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/tasks/'),
        ),
    ]
