# Generated by Django 5.1.1 on 2024-10-08 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_project_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='question',
        ),
        migrations.RemoveField(
            model_name='task',
            name='question_file',
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(blank=True, max_length=300, null=True)),
                ('question_file', models.FileField(blank=True, null=True, upload_to='uploads/questions/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.task')),
            ],
        ),
    ]
