# Generated by Django 5.1.1 on 2024-10-11 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_remove_timer_task_timer_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='added_by',
            new_name='created_by',
        ),
    ]
