# Generated by Django 5.1.1 on 2024-10-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_added_by_task_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.AddField(
            model_name='question',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.project'),
            preserve_default=False,
        ),
    ]
