# Generated by Django 5.1.1 on 2024-10-14 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_question_task_question_project'),
        ('invitations', '0003_invitation_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='app.project'),
            preserve_default=False,
        ),
    ]
